### ISSUE TITLE
 Excuse me，I have some questions to ask

### ISSUE THREAD

**Issue by Doby6** [wyysf-98/Sin3DGen#4]
I would like to ask what is the difference between Quick inference demo.py and generate.py, is the initial parameter different? Also, I want to use my own data to generate scenes, but I don’t understand the operation of svox2. Do I need to train in svox2 to obtain data based on pictures, and then generate scenes in generate.py?

**Comment by wyysf-98** [comment]
Hi, sorry for the late reply due to weekends.
1. 'generate.py' runs the whole generate pipeline, while 'quick_inference_demo.py' is only used for visualization. You should provide the generated mapping field file when using 'quick_inference_demo.py'.
2. For your own data, you can train svox2 using the [modified version](https://github.com/wyysf-98/svox2), which save the ckpt at each pyramid level. Then you can get a sequence of svox2 models of your own data. Run 'generate.py' so that you can get the synthesized results.

**Comment by Doby6** [comment]
Oh, I think I understand. I really appreciate your answer
